{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "70a77f9c",
   "metadata": {},
   "outputs": [],
   "source": [
    "%load_ext autoreload\n",
    "%autoreload 2\n",
    "\n",
    "import asyncio, copy, os, socket, sys, time\n",
    "from functools import partial\n",
    "from multiprocessing import Pool, Process\n",
    "from pathlib import Path\n",
    "from tqdm import tqdm\n",
    "\n",
    "import torch\n",
    "from torch import optim\n",
    "from torch.utils.tensorboard import SummaryWriter\n",
    "\n",
    "sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), \"../\")))\n",
    "from libs import agg, data, fl, log, nn, plot, poison, resnet, sim, wandb\n",
    "from libs.distributed import *\n",
    "from cfgs.fedargs import *"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "8c9749cd",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[34m\u001b[1mwandb\u001b[0m: Currently logged in as: \u001b[33mkasyah\u001b[0m (use `wandb login --relogin` to force relogin)\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: wandb version 0.12.6 is available!  To upgrade, please run:\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m:  $ pip install wandb --upgrade\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "\n",
       "                    Syncing run <strong><a href=\"https://wandb.ai/kasyah/fl-kafka/runs/2lm87rd1\" target=\"_blank\">fedavg-cnn-cifar10-na</a></strong> to <a href=\"https://wandb.ai/kasyah/fl-kafka\" target=\"_blank\">Weights & Biases</a> (<a href=\"https://docs.wandb.com/integrations/jupyter.html\" target=\"_blank\">docs</a>).<br/>\n",
       "\n",
       "                "
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "project = 'fl-kafka'\n",
    "fedargs.epochs = 10\n",
    "fedargs.num_clients = 5\n",
    "fedargs.model = resnet.ResNet18()\n",
    "fedargs.dataset = 'cifar10'\n",
    "name = 'fedavg-cnn-cifar10-na'\n",
    "\n",
    "# Save Logs To File (info | debug | warning | error | critical) [optional]\n",
    "log.init(\"info\")\n",
    "#log.init(\"info\", name)\n",
    "#log.init(\"debug\", name)\n",
    "\n",
    "fedargs.tb = SummaryWriter('../out/runs/' + project + '/' + name, comment=\"fl\")\n",
    "#plot = plot.init(name, project)\n",
    "wb = wandb.init(name, project)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "6a3022ee",
   "metadata": {},
   "outputs": [],
   "source": [
    "use_cuda = fedargs.cuda and torch.cuda.is_available()\n",
    "torch.manual_seed(fedargs.seed)\n",
    "device = torch.device(\"cuda\" if use_cuda else \"cpu\")\n",
    "kwargs = {\"num_workers\": 1, \"pin_memory\": True} if use_cuda else {}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "3e8de969",
   "metadata": {},
   "outputs": [],
   "source": [
    "host = socket.gethostname()\n",
    "clients = [host + \"(\" + str(client + 1) + \")\" for client in range(fedargs.num_clients)]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "618dc172",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Distributed topology\n",
    "dt = Distributed(clients, fedargs.broker_ip, fedargs.schema_ip, fedargs.wait_to_consume)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "e8a71374",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Files already downloaded and verified\n",
      "Files already downloaded and verified\n"
     ]
    }
   ],
   "source": [
    "# Initialize Global and Client models\n",
    "global_model = copy.deepcopy(fedargs.model)\n",
    "# Load Data to clients\n",
    "train_data, test_data = data.load_dataset(fedargs.dataset)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "da8c00ba",
   "metadata": {},
   "outputs": [],
   "source": [
    "clients_data = data.split_data(train_data, clients)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "b7283a3b",
   "metadata": {},
   "outputs": [],
   "source": [
    "client_train_loaders, client_test_loaders = data.load_client_data(clients_data, fedargs.client_batch_size, 0.2, **kwargs)\n",
    "test_loader = torch.utils.data.DataLoader(test_data, batch_size=fedargs.test_batch_size, shuffle=True, **kwargs)\n",
    "\n",
    "client_details = {\n",
    "        client: {\"train_loader\": client_train_loaders[client],\n",
    "                 \"test_loader\": client_test_loaders[client],\n",
    "                 \"model\": copy.deepcopy(global_model),\n",
    "                 \"model_update\": None}\n",
    "        for client in clients\n",
    "    }"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "280fc803",
   "metadata": {},
   "outputs": [],
   "source": [
    "def background(f):\n",
    "    def wrapped(*args, **kwargs):\n",
    "        return asyncio.get_event_loop().run_in_executor(None, f, *args, **kwargs)\n",
    "\n",
    "    return wrapped\n",
    "\n",
    "@background\n",
    "def process(client, epoch, dt, model, train_loader, test_loader, fedargs, device):\n",
    "    log.info(\"Epoch: {}, Processing Client {}\".format(epoch, client))\n",
    "    \n",
    "    # Consume and Average, epoch passed is actually prev epoch, for which we want to consume updates\n",
    "    client_model_updates = dt.consume_model(client, fedargs.topic, model, epoch)\n",
    "    \n",
    "    # Pop one's own update\n",
    "    if client in client_model_updates:\n",
    "        client_model_updates.pop(client)\n",
    "\n",
    "    log.info(\"Epoch: {}, Client {} received {} model update(s) from {}\".format(epoch, client, \n",
    "                                                                               len(client_model_updates), \n",
    "                                                                               list(client_model_updates.keys())))\n",
    "    \n",
    "    if len(client_model_updates) != 0:\n",
    "        model = fl.federated_avg(client_model_updates, model)\n",
    "\n",
    "    # Train    \n",
    "    model_update, model, loss = fedargs.train_func(model, train_loader, \n",
    "                                                   fedargs.learning_rate,\n",
    "                                                   fedargs.weight_decay,\n",
    "                                                   fedargs.local_rounds, device)\n",
    "\n",
    "    # Publish\n",
    "    epoch = epoch + 1\n",
    "    dt.produce_model(client, fedargs.topic, model_update, epoch)\n",
    "\n",
    "    log.jsondebug(loss, \"Epoch {} : Federated Training loss, Client {}\".format(epoch, client))\n",
    "    log.modeldebug(model, \"Epoch {}: Client {} Update\".format(epoch, client))\n",
    "\n",
    "    # Test, Plot and Log\n",
    "    test_output = fedargs.eval_func(model, test_loader, device)\n",
    "    fedargs.tb.add_scalar(\"Accuracy/\" + client, test_output[\"accuracy\"], epoch)\n",
    "    fedargs.tb.add_scalar(\"Test Loss/\" + client, test_output[\"test_loss\"], epoch)\n",
    "    #plot.alog(client, {epoch: {\"time\": time.time(), \"acc\": test_output[\"accuracy\"], \"loss\": test_output[\"test_loss\"]}})\n",
    "    wb.log({client: {\"epoch\": epoch, \"time\": time.time(), \"acc\": test_output[\"accuracy\"], \"loss\": test_output[\"test_loss\"]}})\n",
    "    log.jsoninfo(test_output, \"Test Outut after Epoch {} of {} for Client {}\".format(epoch, fedargs.epochs, client))\n",
    "\n",
    "    return model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "fc40c00d",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  0%|          | 0/10 [00:00<?, ?it/s]2021-11-08 13:22:16,272 - <ipython-input-10-d06f8893748b>::<module>(l:6) : Federated Training Epoch 0 of 10 [MainProcess : MainThread (INFO)]\n",
      "2021-11-08 13:22:16,376 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 0, Processing Client bladecluster.iitp.org(4) [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 13:22:16,377 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 0, Processing Client bladecluster.iitp.org(5) [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 13:22:16,378 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 0, Processing Client bladecluster.iitp.org(3) [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 13:22:16,381 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 0, Processing Client bladecluster.iitp.org(2) [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 13:22:16,382 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 0, Processing Client bladecluster.iitp.org(1) [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 13:22:17,453 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 0, Client bladecluster.iitp.org(1) received 0 model update(s) from [] [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 13:22:17,483 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 0, Client bladecluster.iitp.org(4) received 0 model update(s) from [] [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 13:22:17,485 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 0, Client bladecluster.iitp.org(2) received 0 model update(s) from [] [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 13:22:17,511 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 0, Client bladecluster.iitp.org(5) received 0 model update(s) from [] [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 13:22:17,568 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 0, Client bladecluster.iitp.org(3) received 0 model update(s) from [] [MainProcess : asyncio_2 (INFO)]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception list index out of range occured consuming update for client bladecluster.iitp.org(1)\n",
      "Exception list index out of range occured consuming update for client bladecluster.iitp.org(2)Exception list index out of range occured consuming update for client bladecluster.iitp.org(4)\n",
      "\n",
      "Exception list index out of range occured consuming update for client bladecluster.iitp.org(5)\n",
      "Exception list index out of range occured consuming update for client bladecluster.iitp.org(3)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-11-08 13:26:45,041 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 13:26:45,406 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_1 (ERROR)]\n",
      "2021-11-08 13:26:45,424 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 13:26:47,856 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 13:26:48,174 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_4 (ERROR)]\n",
      "2021-11-08 13:26:48,196 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 13:26:51,732 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 13:26:52,113 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_0 (ERROR)]\n",
      "2021-11-08 13:26:52,134 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 13:26:56,493 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 13:26:56,967 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_3 (ERROR)]\n",
      "2021-11-08 13:26:56,996 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 13:27:06,922 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 1 of 10 for Client bladecluster.iitp.org(2) {\n",
      "    \"accuracy\": 32.35,\n",
      "    \"correct\": 647,\n",
      "    \"test_loss\": -23.68823419189453\n",
      "} [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 13:27:07,445 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 1 of 10 for Client bladecluster.iitp.org(5) {\n",
      "    \"accuracy\": 30.55,\n",
      "    \"correct\": 611,\n",
      "    \"test_loss\": -21.68028579711914\n",
      "} [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 13:27:08,456 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 1 of 10 for Client bladecluster.iitp.org(1) {\n",
      "    \"accuracy\": 33.7,\n",
      "    \"correct\": 674,\n",
      "    \"test_loss\": -21.712553146362303\n",
      "} [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 13:27:09,657 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 1 of 10 for Client bladecluster.iitp.org(4) {\n",
      "    \"accuracy\": 29.2,\n",
      "    \"correct\": 584,\n",
      "    \"test_loss\": -23.55170195007324\n",
      "} [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 13:27:15,147 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 13:27:15,386 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_2 (ERROR)]\n",
      "2021-11-08 13:27:15,400 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 13:27:23,108 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 1 of 10 for Client bladecluster.iitp.org(3) {\n",
      "    \"accuracy\": 33.1,\n",
      "    \"correct\": 662,\n",
      "    \"test_loss\": -22.724614013671875\n",
      "} [MainProcess : asyncio_2 (INFO)]\n",
      " 10%|█         | 1/10 [05:07<46:04, 307.20s/it]2021-11-08 13:27:23,136 - <ipython-input-10-d06f8893748b>::<module>(l:6) : Federated Training Epoch 1 of 10 [MainProcess : MainThread (INFO)]\n",
      "2021-11-08 13:27:23,186 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 1, Processing Client bladecluster.iitp.org(2) [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 13:27:23,219 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 1, Processing Client bladecluster.iitp.org(1) [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 13:27:23,246 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 1, Processing Client bladecluster.iitp.org(4) [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 13:27:23,252 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 1, Processing Client bladecluster.iitp.org(3) [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 13:27:23,254 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 1, Processing Client bladecluster.iitp.org(5) [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 13:27:24,313 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 1, Client bladecluster.iitp.org(2) received 0 model update(s) from [] [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 13:27:24,314 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 1, Client bladecluster.iitp.org(1) received 0 model update(s) from [] [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 13:27:24,315 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 1, Client bladecluster.iitp.org(5) received 0 model update(s) from [] [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 13:27:24,330 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 1, Client bladecluster.iitp.org(3) received 0 model update(s) from [] [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 13:27:24,377 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 1, Client bladecluster.iitp.org(4) received 0 model update(s) from [] [MainProcess : asyncio_3 (INFO)]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception list index out of range occured consuming update for client bladecluster.iitp.org(2)\n",
      "Exception list index out of range occured consuming update for client bladecluster.iitp.org(1)\n",
      "Exception list index out of range occured consuming update for client bladecluster.iitp.org(5)Exception list index out of range occured consuming update for client bladecluster.iitp.org(3)\n",
      "Exception list index out of range occured consuming update for client bladecluster.iitp.org(4)\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-11-08 13:31:36,600 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 13:31:36,982 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_0 (ERROR)]\n",
      "2021-11-08 13:31:37,011 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 13:31:39,666 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 13:31:39,995 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_4 (ERROR)]\n",
      "2021-11-08 13:31:40,015 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 13:31:44,086 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 13:31:44,480 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_1 (ERROR)]\n",
      "2021-11-08 13:31:44,504 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 13:31:49,735 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 13:31:50,102 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_3 (ERROR)]\n",
      "2021-11-08 13:31:50,122 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 13:31:58,029 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 2 of 10 for Client bladecluster.iitp.org(3) {\n",
      "    \"accuracy\": 31.5,\n",
      "    \"correct\": 630,\n",
      "    \"test_loss\": -42.61183261108398\n",
      "} [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 13:31:58,851 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 2 of 10 for Client bladecluster.iitp.org(2) {\n",
      "    \"accuracy\": 32.45,\n",
      "    \"correct\": 649,\n",
      "    \"test_loss\": -41.84101254272461\n",
      "} [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 13:32:00,797 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 13:32:01,117 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_2 (ERROR)]\n",
      "2021-11-08 13:32:01,137 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 13:32:03,451 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 2 of 10 for Client bladecluster.iitp.org(1) {\n",
      "    \"accuracy\": 36.4,\n",
      "    \"correct\": 728,\n",
      "    \"test_loss\": -43.53588003540039\n",
      "} [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 13:32:05,130 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 2 of 10 for Client bladecluster.iitp.org(4) {\n",
      "    \"accuracy\": 38.3,\n",
      "    \"correct\": 766,\n",
      "    \"test_loss\": -39.07800372314453\n",
      "} [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 13:32:10,314 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 2 of 10 for Client bladecluster.iitp.org(5) {\n",
      "    \"accuracy\": 39.800000000000004,\n",
      "    \"correct\": 796,\n",
      "    \"test_loss\": -43.103600677490235\n",
      "} [MainProcess : asyncio_2 (INFO)]\n",
      " 20%|██        | 2/10 [09:54<39:23, 295.44s/it]2021-11-08 13:32:10,358 - <ipython-input-10-d06f8893748b>::<module>(l:6) : Federated Training Epoch 2 of 10 [MainProcess : MainThread (INFO)]\n",
      "2021-11-08 13:32:10,459 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 2, Processing Client bladecluster.iitp.org(4) [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 13:32:10,473 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 2, Processing Client bladecluster.iitp.org(1) [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 13:32:10,482 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 2, Processing Client bladecluster.iitp.org(2) [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 13:32:10,486 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 2, Processing Client bladecluster.iitp.org(5) [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 13:32:10,490 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 2, Processing Client bladecluster.iitp.org(3) [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 13:32:11,675 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 2, Client bladecluster.iitp.org(4) received 0 model update(s) from [] [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 13:32:11,679 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 2, Client bladecluster.iitp.org(5) received 0 model update(s) from [] [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 13:32:11,711 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 2, Client bladecluster.iitp.org(2) received 0 model update(s) from [] [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 13:32:11,754 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 2, Client bladecluster.iitp.org(1) received 0 model update(s) from [] [MainProcess : asyncio_0 (INFO)]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception list index out of range occured consuming update for client bladecluster.iitp.org(5)\n",
      "Exception list index out of range occured consuming update for client bladecluster.iitp.org(4)\n",
      "Exception list index out of range occured consuming update for client bladecluster.iitp.org(2)\n",
      "Exception list index out of range occured consuming update for client bladecluster.iitp.org(1)\n",
      "Exception list index out of range occured consuming update for client bladecluster.iitp.org(3)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-11-08 13:32:11,814 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 2, Client bladecluster.iitp.org(3) received 0 model update(s) from [] [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 13:36:21,266 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 13:36:22,734 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_3 (ERROR)]\n",
      "2021-11-08 13:36:23,776 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 13:36:23,782 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 13:36:24,212 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_0 (ERROR)]\n",
      "2021-11-08 13:36:24,241 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 13:36:32,096 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 13:36:32,527 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_4 (ERROR)]\n",
      "2021-11-08 13:36:32,550 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 13:36:42,256 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 13:36:42,603 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_1 (ERROR)]\n",
      "2021-11-08 13:36:42,626 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 13:36:42,788 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 3 of 10 for Client bladecluster.iitp.org(4) {\n",
      "    \"accuracy\": 37.75,\n",
      "    \"correct\": 755,\n",
      "    \"test_loss\": -64.06220404052735\n",
      "} [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 13:36:43,368 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 3 of 10 for Client bladecluster.iitp.org(1) {\n",
      "    \"accuracy\": 43.45,\n",
      "    \"correct\": 869,\n",
      "    \"test_loss\": -62.27058361816406\n",
      "} [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 13:36:48,118 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 3 of 10 for Client bladecluster.iitp.org(2) {\n",
      "    \"accuracy\": 34.1,\n",
      "    \"correct\": 682,\n",
      "    \"test_loss\": -66.73648266601562\n",
      "} [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 13:36:50,312 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 13:36:50,662 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_2 (ERROR)]\n",
      "2021-11-08 13:36:50,680 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 13:36:55,006 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 3 of 10 for Client bladecluster.iitp.org(3) {\n",
      "    \"accuracy\": 42.25,\n",
      "    \"correct\": 845,\n",
      "    \"test_loss\": -64.97990576171875\n",
      "} [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 13:36:58,982 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 3 of 10 for Client bladecluster.iitp.org(5) {\n",
      "    \"accuracy\": 41.449999999999996,\n",
      "    \"correct\": 829,\n",
      "    \"test_loss\": -63.288499389648436\n",
      "} [MainProcess : asyncio_2 (INFO)]\n",
      " 30%|███       | 3/10 [14:43<34:06, 292.35s/it]2021-11-08 13:36:59,016 - <ipython-input-10-d06f8893748b>::<module>(l:6) : Federated Training Epoch 3 of 10 [MainProcess : MainThread (INFO)]\n",
      "2021-11-08 13:36:59,054 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 3, Processing Client bladecluster.iitp.org(1) [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 13:36:59,118 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 3, Processing Client bladecluster.iitp.org(5) [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 13:36:59,119 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 3, Processing Client bladecluster.iitp.org(4) [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 13:36:59,136 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 3, Processing Client bladecluster.iitp.org(2) [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 13:36:59,139 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 3, Processing Client bladecluster.iitp.org(3) [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 13:37:00,263 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 3, Client bladecluster.iitp.org(5) received 0 model update(s) from [] [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 13:37:00,284 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 3, Client bladecluster.iitp.org(2) received 0 model update(s) from [] [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 13:37:00,304 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 3, Client bladecluster.iitp.org(4) received 0 model update(s) from [] [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 13:37:00,352 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 3, Client bladecluster.iitp.org(3) received 0 model update(s) from [] [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 13:37:00,404 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 3, Client bladecluster.iitp.org(1) received 0 model update(s) from [] [MainProcess : asyncio_3 (INFO)]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception list index out of range occured consuming update for client bladecluster.iitp.org(5)\n",
      "Exception list index out of range occured consuming update for client bladecluster.iitp.org(2)\n",
      "Exception list index out of range occured consuming update for client bladecluster.iitp.org(4)\n",
      "Exception list index out of range occured consuming update for client bladecluster.iitp.org(3)\n",
      "Exception list index out of range occured consuming update for client bladecluster.iitp.org(1)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-11-08 13:41:12,581 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 13:41:12,885 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_3 (ERROR)]\n",
      "2021-11-08 13:41:12,911 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 13:41:18,557 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 13:41:18,984 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_0 (ERROR)]\n",
      "2021-11-08 13:41:19,014 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 13:41:21,312 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 13:41:21,681 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_4 (ERROR)]\n",
      "2021-11-08 13:41:21,701 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 13:41:33,314 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 13:41:33,654 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_1 (ERROR)]\n",
      "2021-11-08 13:41:33,676 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 13:41:34,102 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 4 of 10 for Client bladecluster.iitp.org(1) {\n",
      "    \"accuracy\": 42.1,\n",
      "    \"correct\": 842,\n",
      "    \"test_loss\": -87.45095849609375\n",
      "} [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 13:41:37,609 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 4 of 10 for Client bladecluster.iitp.org(2) {\n",
      "    \"accuracy\": 43.8,\n",
      "    \"correct\": 876,\n",
      "    \"test_loss\": -83.44517230224609\n",
      "} [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 13:41:37,728 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 4 of 10 for Client bladecluster.iitp.org(3) {\n",
      "    \"accuracy\": 42.9,\n",
      "    \"correct\": 858,\n",
      "    \"test_loss\": -87.60239276123046\n",
      "} [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 13:41:41,329 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 13:41:41,712 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_2 (ERROR)]\n",
      "2021-11-08 13:41:41,732 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 13:41:45,485 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 4 of 10 for Client bladecluster.iitp.org(4) {\n",
      "    \"accuracy\": 42.5,\n",
      "    \"correct\": 850,\n",
      "    \"test_loss\": -86.30595532226563\n",
      "} [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 13:41:50,522 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 4 of 10 for Client bladecluster.iitp.org(5) {\n",
      "    \"accuracy\": 38.9,\n",
      "    \"correct\": 778,\n",
      "    \"test_loss\": -84.5968226928711\n",
      "} [MainProcess : asyncio_2 (INFO)]\n",
      " 40%|████      | 4/10 [19:34<29:12, 292.03s/it]2021-11-08 13:41:50,563 - <ipython-input-10-d06f8893748b>::<module>(l:6) : Federated Training Epoch 4 of 10 [MainProcess : MainThread (INFO)]\n",
      "2021-11-08 13:41:50,629 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 4, Processing Client bladecluster.iitp.org(2) [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 13:41:50,649 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 4, Processing Client bladecluster.iitp.org(1) [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 13:41:50,658 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 4, Processing Client bladecluster.iitp.org(5) [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 13:41:50,668 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 4, Processing Client bladecluster.iitp.org(4) [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 13:41:50,675 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 4, Processing Client bladecluster.iitp.org(3) [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 13:41:51,788 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 4, Client bladecluster.iitp.org(4) received 0 model update(s) from [] [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 13:41:51,794 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 4, Client bladecluster.iitp.org(2) received 0 model update(s) from [] [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 13:41:51,797 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 4, Client bladecluster.iitp.org(5) received 0 model update(s) from [] [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 13:41:51,817 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 4, Client bladecluster.iitp.org(1) received 0 model update(s) from [] [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 13:41:51,853 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 4, Client bladecluster.iitp.org(3) received 0 model update(s) from [] [MainProcess : asyncio_4 (INFO)]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception list index out of range occured consuming update for client bladecluster.iitp.org(5)Exception list index out of range occured consuming update for client bladecluster.iitp.org(2)\n",
      "\n",
      "Exception list index out of range occured consuming update for client bladecluster.iitp.org(4)Exception list index out of range occured consuming update for client bladecluster.iitp.org(1)\n",
      "\n",
      "Exception list index out of range occured consuming update for client bladecluster.iitp.org(3)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-11-08 13:45:59,961 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 13:46:00,332 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_0 (ERROR)]\n",
      "2021-11-08 13:46:00,359 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 13:46:04,565 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 13:46:04,765 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_3 (ERROR)]\n",
      "2021-11-08 13:46:04,780 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 13:46:09,930 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 13:46:10,285 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_4 (ERROR)]\n",
      "2021-11-08 13:46:10,309 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 13:46:16,135 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 13:46:16,488 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_1 (ERROR)]\n",
      "2021-11-08 13:46:16,509 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 13:46:21,149 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 5 of 10 for Client bladecluster.iitp.org(2) {\n",
      "    \"accuracy\": 46.45,\n",
      "    \"correct\": 929,\n",
      "    \"test_loss\": -105.21567041015625\n",
      "} [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 13:46:23,439 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 5 of 10 for Client bladecluster.iitp.org(1) {\n",
      "    \"accuracy\": 44.800000000000004,\n",
      "    \"correct\": 896,\n",
      "    \"test_loss\": -109.95980828857422\n",
      "} [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 13:46:25,839 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 5 of 10 for Client bladecluster.iitp.org(3) {\n",
      "    \"accuracy\": 42.05,\n",
      "    \"correct\": 841,\n",
      "    \"test_loss\": -104.9812114868164\n",
      "} [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 13:46:28,325 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 13:46:28,646 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_2 (ERROR)]\n",
      "2021-11-08 13:46:28,664 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 13:46:30,515 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 5 of 10 for Client bladecluster.iitp.org(4) {\n",
      "    \"accuracy\": 43.75,\n",
      "    \"correct\": 875,\n",
      "    \"test_loss\": -109.0660576171875\n",
      "} [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 13:46:37,327 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 5 of 10 for Client bladecluster.iitp.org(5) {\n",
      "    \"accuracy\": 43.1,\n",
      "    \"correct\": 862,\n",
      "    \"test_loss\": -109.28980480957031\n",
      "} [MainProcess : asyncio_2 (INFO)]\n",
      " 50%|█████     | 5/10 [24:21<24:10, 290.15s/it]2021-11-08 13:46:37,360 - <ipython-input-10-d06f8893748b>::<module>(l:6) : Federated Training Epoch 5 of 10 [MainProcess : MainThread (INFO)]\n",
      "2021-11-08 13:46:37,485 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 5, Processing Client bladecluster.iitp.org(3) [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 13:46:37,503 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 5, Processing Client bladecluster.iitp.org(5) [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 13:46:37,508 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 5, Processing Client bladecluster.iitp.org(1) [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 13:46:37,511 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 5, Processing Client bladecluster.iitp.org(2) [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 13:46:37,511 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 5, Processing Client bladecluster.iitp.org(4) [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 13:46:47,579 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 5, Client bladecluster.iitp.org(5) received 0 model update(s) from [] [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 13:46:47,615 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 5, Client bladecluster.iitp.org(4) received 0 model update(s) from [] [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 13:46:47,616 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 5, Client bladecluster.iitp.org(3) received 0 model update(s) from [] [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 13:46:47,645 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 5, Client bladecluster.iitp.org(1) received 0 model update(s) from [] [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 13:46:47,655 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 5, Client bladecluster.iitp.org(2) received 0 model update(s) from [] [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 13:50:59,616 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 13:50:59,957 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_3 (ERROR)]\n",
      "2021-11-08 13:50:59,975 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 13:51:03,188 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 13:51:03,504 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_4 (ERROR)]\n",
      "2021-11-08 13:51:03,524 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 13:51:06,525 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 13:51:06,862 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_0 (ERROR)]\n",
      "2021-11-08 13:51:06,883 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 13:51:19,633 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 13:51:19,988 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_1 (ERROR)]\n",
      "2021-11-08 13:51:20,009 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 13:51:21,066 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 6 of 10 for Client bladecluster.iitp.org(2) {\n",
      "    \"accuracy\": 44.45,\n",
      "    \"correct\": 889,\n",
      "    \"test_loss\": -128.9858916015625\n",
      "} [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 13:51:22,130 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 6 of 10 for Client bladecluster.iitp.org(3) {\n",
      "    \"accuracy\": 45.7,\n",
      "    \"correct\": 914,\n",
      "    \"test_loss\": -135.7254673461914\n",
      "} [MainProcess : asyncio_4 (INFO)]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-11-08 13:51:23,241 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 6 of 10 for Client bladecluster.iitp.org(1) {\n",
      "    \"accuracy\": 42.1,\n",
      "    \"correct\": 842,\n",
      "    \"test_loss\": -130.49165563964843\n",
      "} [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 13:51:27,261 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 13:51:27,598 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_2 (ERROR)]\n",
      "2021-11-08 13:51:27,616 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 13:51:32,226 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 6 of 10 for Client bladecluster.iitp.org(4) {\n",
      "    \"accuracy\": 42.449999999999996,\n",
      "    \"correct\": 849,\n",
      "    \"test_loss\": -130.22928894042968\n",
      "} [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 13:51:35,768 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 6 of 10 for Client bladecluster.iitp.org(5) {\n",
      "    \"accuracy\": 40.550000000000004,\n",
      "    \"correct\": 811,\n",
      "    \"test_loss\": -135.20107971191408\n",
      "} [MainProcess : asyncio_2 (INFO)]\n",
      " 60%|██████    | 6/10 [29:19<19:31, 292.96s/it]2021-11-08 13:51:35,790 - <ipython-input-10-d06f8893748b>::<module>(l:6) : Federated Training Epoch 6 of 10 [MainProcess : MainThread (INFO)]\n",
      "2021-11-08 13:51:35,823 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 6, Processing Client bladecluster.iitp.org(2) [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 13:51:35,859 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 6, Processing Client bladecluster.iitp.org(4) [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 13:51:35,878 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 6, Processing Client bladecluster.iitp.org(1) [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 13:51:35,884 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 6, Processing Client bladecluster.iitp.org(3) [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 13:51:35,891 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 6, Processing Client bladecluster.iitp.org(5) [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 13:51:45,868 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 6, Client bladecluster.iitp.org(2) received 0 model update(s) from [] [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 13:51:45,967 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 6, Client bladecluster.iitp.org(4) received 0 model update(s) from [] [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 13:51:45,997 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 6, Client bladecluster.iitp.org(1) received 0 model update(s) from [] [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 13:51:46,000 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 6, Client bladecluster.iitp.org(5) received 0 model update(s) from [] [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 13:51:46,005 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 6, Client bladecluster.iitp.org(3) received 0 model update(s) from [] [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 13:55:56,341 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 13:55:56,732 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_4 (ERROR)]\n",
      "2021-11-08 13:55:56,753 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 13:56:00,138 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 13:56:00,432 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_0 (ERROR)]\n",
      "2021-11-08 13:56:00,453 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 13:56:04,620 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 13:56:04,961 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_3 (ERROR)]\n",
      "2021-11-08 13:56:04,982 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 13:56:15,412 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 13:56:15,739 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_1 (ERROR)]\n",
      "2021-11-08 13:56:15,759 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 13:56:18,553 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 7 of 10 for Client bladecluster.iitp.org(2) {\n",
      "    \"accuracy\": 44.75,\n",
      "    \"correct\": 895,\n",
      "    \"test_loss\": -161.48155065917967\n",
      "} [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 13:56:19,824 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 7 of 10 for Client bladecluster.iitp.org(3) {\n",
      "    \"accuracy\": 41.699999999999996,\n",
      "    \"correct\": 834,\n",
      "    \"test_loss\": -158.1014775390625\n",
      "} [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 13:56:22,029 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 13:56:22,367 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_2 (ERROR)]\n",
      "2021-11-08 13:56:22,384 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 13:56:23,690 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 7 of 10 for Client bladecluster.iitp.org(1) {\n",
      "    \"accuracy\": 47.15,\n",
      "    \"correct\": 943,\n",
      "    \"test_loss\": -157.03246630859374\n",
      "} [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 13:56:29,049 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 7 of 10 for Client bladecluster.iitp.org(4) {\n",
      "    \"accuracy\": 44.25,\n",
      "    \"correct\": 885,\n",
      "    \"test_loss\": -157.68999267578124\n",
      "} [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 13:56:31,341 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 7 of 10 for Client bladecluster.iitp.org(5) {\n",
      "    \"accuracy\": 38.4,\n",
      "    \"correct\": 768,\n",
      "    \"test_loss\": -156.77268823242187\n",
      "} [MainProcess : asyncio_2 (INFO)]\n",
      " 70%|███████   | 7/10 [34:15<14:41, 293.82s/it]2021-11-08 13:56:31,388 - <ipython-input-10-d06f8893748b>::<module>(l:6) : Federated Training Epoch 7 of 10 [MainProcess : MainThread (INFO)]\n",
      "2021-11-08 13:56:31,483 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 7, Processing Client bladecluster.iitp.org(2) [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 13:56:31,497 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 7, Processing Client bladecluster.iitp.org(4) [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 13:56:31,498 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 7, Processing Client bladecluster.iitp.org(5) [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 13:56:31,500 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 7, Processing Client bladecluster.iitp.org(3) [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 13:56:31,505 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 7, Processing Client bladecluster.iitp.org(1) [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 13:56:41,523 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 7, Client bladecluster.iitp.org(2) received 0 model update(s) from [] [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 13:56:41,583 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 7, Client bladecluster.iitp.org(4) received 0 model update(s) from [] [MainProcess : asyncio_1 (INFO)]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-11-08 13:56:41,598 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 7, Client bladecluster.iitp.org(5) received 0 model update(s) from [] [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 13:56:41,613 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 7, Client bladecluster.iitp.org(3) received 0 model update(s) from [] [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 13:56:41,618 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 7, Client bladecluster.iitp.org(1) received 0 model update(s) from [] [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 14:00:53,829 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 14:00:54,186 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_3 (ERROR)]\n",
      "2021-11-08 14:00:54,217 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 14:00:56,336 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 14:00:56,564 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_0 (ERROR)]\n",
      "2021-11-08 14:00:56,580 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 14:00:59,114 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 14:00:59,415 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_4 (ERROR)]\n",
      "2021-11-08 14:00:59,434 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 14:01:13,053 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 8 of 10 for Client bladecluster.iitp.org(3) {\n",
      "    \"accuracy\": 44.35,\n",
      "    \"correct\": 887,\n",
      "    \"test_loss\": -185.453056640625\n",
      "} [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 14:01:13,158 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 8 of 10 for Client bladecluster.iitp.org(2) {\n",
      "    \"accuracy\": 47.4,\n",
      "    \"correct\": 948,\n",
      "    \"test_loss\": -192.6974375\n",
      "} [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 14:01:13,662 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 8 of 10 for Client bladecluster.iitp.org(1) {\n",
      "    \"accuracy\": 38.1,\n",
      "    \"correct\": 762,\n",
      "    \"test_loss\": -192.7376231689453\n",
      "} [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 14:01:15,580 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 14:01:15,862 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_1 (ERROR)]\n",
      "2021-11-08 14:01:15,877 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 14:01:19,009 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 14:01:19,342 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_2 (ERROR)]\n",
      "2021-11-08 14:01:19,365 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 14:01:27,221 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 8 of 10 for Client bladecluster.iitp.org(4) {\n",
      "    \"accuracy\": 44.15,\n",
      "    \"correct\": 883,\n",
      "    \"test_loss\": -193.0132421875\n",
      "} [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 14:01:28,132 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 8 of 10 for Client bladecluster.iitp.org(5) {\n",
      "    \"accuracy\": 39.800000000000004,\n",
      "    \"correct\": 796,\n",
      "    \"test_loss\": -189.4997717285156\n",
      "} [MainProcess : asyncio_2 (INFO)]\n",
      " 80%|████████  | 8/10 [39:12<09:49, 294.77s/it]2021-11-08 14:01:28,175 - <ipython-input-10-d06f8893748b>::<module>(l:6) : Federated Training Epoch 8 of 10 [MainProcess : MainThread (INFO)]\n",
      "2021-11-08 14:01:28,281 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 8, Processing Client bladecluster.iitp.org(5) [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 14:01:28,281 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 8, Processing Client bladecluster.iitp.org(4) [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 14:01:28,282 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 8, Processing Client bladecluster.iitp.org(1) [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 14:01:28,283 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 8, Processing Client bladecluster.iitp.org(3) [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 14:01:28,283 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 8, Processing Client bladecluster.iitp.org(2) [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 14:01:38,326 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 8, Client bladecluster.iitp.org(5) received 0 model update(s) from [] [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 14:01:38,381 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 8, Client bladecluster.iitp.org(1) received 0 model update(s) from [] [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 14:01:38,418 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 8, Client bladecluster.iitp.org(2) received 0 model update(s) from [] [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 14:01:38,421 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 8, Client bladecluster.iitp.org(3) received 0 model update(s) from [] [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 14:01:38,441 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 8, Client bladecluster.iitp.org(4) received 0 model update(s) from [] [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 14:05:45,729 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 14:05:46,087 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_4 (ERROR)]\n",
      "2021-11-08 14:05:46,106 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 14:05:50,448 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 14:05:50,820 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_0 (ERROR)]\n",
      "2021-11-08 14:05:50,850 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 14:05:54,225 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 14:05:54,538 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_3 (ERROR)]\n",
      "2021-11-08 14:05:54,560 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 14:06:03,084 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 14:06:03,446 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_1 (ERROR)]\n",
      "2021-11-08 14:06:03,464 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_1 (INFO)]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-11-08 14:06:07,232 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 9 of 10 for Client bladecluster.iitp.org(3) {\n",
      "    \"accuracy\": 43.6,\n",
      "    \"correct\": 872,\n",
      "    \"test_loss\": -225.0173839111328\n",
      "} [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 14:06:09,572 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 9 of 10 for Client bladecluster.iitp.org(2) {\n",
      "    \"accuracy\": 45.4,\n",
      "    \"correct\": 908,\n",
      "    \"test_loss\": -214.16035278320314\n",
      "} [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 14:06:11,404 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 14:06:11,762 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_2 (ERROR)]\n",
      "2021-11-08 14:06:11,780 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 14:06:12,640 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 9 of 10 for Client bladecluster.iitp.org(1) {\n",
      "    \"accuracy\": 42.8,\n",
      "    \"correct\": 856,\n",
      "    \"test_loss\": -221.85215368652345\n",
      "} [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 14:06:16,562 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 9 of 10 for Client bladecluster.iitp.org(4) {\n",
      "    \"accuracy\": 43.5,\n",
      "    \"correct\": 870,\n",
      "    \"test_loss\": -223.60181713867186\n",
      "} [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 14:06:21,165 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 9 of 10 for Client bladecluster.iitp.org(5) {\n",
      "    \"accuracy\": 34.75,\n",
      "    \"correct\": 695,\n",
      "    \"test_loss\": -225.274640625\n",
      "} [MainProcess : asyncio_2 (INFO)]\n",
      " 90%|█████████ | 9/10 [44:05<04:54, 294.22s/it]2021-11-08 14:06:21,207 - <ipython-input-10-d06f8893748b>::<module>(l:6) : Federated Training Epoch 9 of 10 [MainProcess : MainThread (INFO)]\n",
      "2021-11-08 14:06:21,300 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 9, Processing Client bladecluster.iitp.org(2) [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 14:06:21,333 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 9, Processing Client bladecluster.iitp.org(3) [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 14:06:21,342 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 9, Processing Client bladecluster.iitp.org(4) [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 14:06:21,342 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 9, Processing Client bladecluster.iitp.org(1) [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 14:06:21,345 - <ipython-input-9-c3c9e283dc74>::process(l:9) : Epoch: 9, Processing Client bladecluster.iitp.org(5) [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 14:06:31,452 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 9, Client bladecluster.iitp.org(4) received 0 model update(s) from [] [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 14:06:31,487 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 9, Client bladecluster.iitp.org(2) received 0 model update(s) from [] [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 14:06:31,500 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 9, Client bladecluster.iitp.org(3) received 0 model update(s) from [] [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 14:06:31,501 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 9, Client bladecluster.iitp.org(1) received 0 model update(s) from [] [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 14:06:31,503 - <ipython-input-9-c3c9e283dc74>::process(l:18) : Epoch: 9, Client bladecluster.iitp.org(5) received 0 model update(s) from [] [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 14:10:47,580 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 14:10:47,910 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_4 (ERROR)]\n",
      "2021-11-08 14:10:47,929 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 14:10:50,107 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 14:10:50,483 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_0 (ERROR)]\n",
      "2021-11-08 14:10:50,503 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 14:10:54,500 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 14:10:54,817 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_3 (ERROR)]\n",
      "2021-11-08 14:10:54,837 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 14:11:03,167 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 14:11:03,494 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_1 (ERROR)]\n",
      "2021-11-08 14:11:03,518 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 14:11:09,493 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 10 of 10 for Client bladecluster.iitp.org(1) {\n",
      "    \"accuracy\": 42.199999999999996,\n",
      "    \"correct\": 844,\n",
      "    \"test_loss\": -250.46399536132813\n",
      "} [MainProcess : asyncio_4 (INFO)]\n",
      "2021-11-08 14:11:09,555 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 10 of 10 for Client bladecluster.iitp.org(2) {\n",
      "    \"accuracy\": 41.949999999999996,\n",
      "    \"correct\": 839,\n",
      "    \"test_loss\": -235.93682360839844\n",
      "} [MainProcess : asyncio_0 (INFO)]\n",
      "2021-11-08 14:11:11,285 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 10 of 10 for Client bladecluster.iitp.org(3) {\n",
      "    \"accuracy\": 39.300000000000004,\n",
      "    \"correct\": 786,\n",
      "    \"test_loss\": -250.79374755859374\n",
      "} [MainProcess : asyncio_3 (INFO)]\n",
      "2021-11-08 14:11:12,974 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:56) : Producing user records to topic pyflx. ^C to exit. [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 14:11:13,299 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:64) : Exception raised [MainProcess : asyncio_2 (ERROR)]\n",
      "2021-11-08 14:11:13,318 - /home/harsh_1921cs01/hub/AgroFed/fl/libs/protobuf_producer.py::produce(l:66) : Flushing records... [MainProcess : asyncio_2 (INFO)]\n",
      "2021-11-08 14:11:17,147 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 10 of 10 for Client bladecluster.iitp.org(4) {\n",
      "    \"accuracy\": 45.0,\n",
      "    \"correct\": 900,\n",
      "    \"test_loss\": -241.77782495117188\n",
      "} [MainProcess : asyncio_1 (INFO)]\n",
      "2021-11-08 14:11:21,608 - <ipython-input-9-c3c9e283dc74>::process(l:44) : Test Outut after Epoch 10 of 10 for Client bladecluster.iitp.org(5) {\n",
      "    \"accuracy\": 37.8,\n",
      "    \"correct\": 756,\n",
      "    \"test_loss\": -260.19294213867187\n",
      "} [MainProcess : asyncio_2 (INFO)]\n",
      "100%|██████████| 10/10 [49:05<00:00, 294.57s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2945.708108663559\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Network error resolved after 0:00:42.729678, resuming normal operation.\n"
     ]
    }
   ],
   "source": [
    "import time\n",
    "start_time = time.time()\n",
    "\n",
    "# Federated Training\n",
    "for epoch in tqdm(range(fedargs.epochs)):\n",
    "    log.info(\"Federated Training Epoch {} of {}\".format(epoch, fedargs.epochs))\n",
    "\n",
    "    # Clients  \n",
    "    tasks = [process(client, epoch, dt, client_details[client]['model'],\n",
    "                     client_details[client]['train_loader'],\n",
    "                     client_details[client]['test_loader'],\n",
    "                     fedargs, device) for client in clients]\n",
    "    try:\n",
    "        updates = fedargs.loop.run_until_complete(asyncio.gather(*tasks))\n",
    "    except KeyboardInterrupt as e:\n",
    "        log.error(\"Caught keyboard interrupt. Canceling tasks...\")\n",
    "        tasks.cancel()\n",
    "        fedargs.loop.run_forever()\n",
    "        tasks.exception()\n",
    "    \n",
    "    for client, update in zip(clients, updates):\n",
    "        client_details[client]['model'] = update\n",
    "    \n",
    "print(time.time() - start_time)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "41c8617e",
   "metadata": {
    "deletable": false,
    "editable": false
   },
   "source": [
    "<h1> End </h1>"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:syft]",
   "language": "python",
   "name": "conda-env-syft-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
